export const SCALE = [0,1,2] as const;
export type ScoreValue = typeof SCALE[number];
export const SCALE_LABELS: Record<ScoreValue,string> = { 0:"Below standard", 1:"Meets standard", 2:"Above standard" };
export type CriterionKey = "focus"|"content"|"interactivity"|"credibility";
export const CRITERIA = [
  { key:"focus", order:1, title:"Facilitation Focus", question:"How relevant is the session to facilitation?", isGate:true, anchors:{0:"Session is oriented towards training, coaching, or a topic outside facilitation. Any overlap with facilitation is incidental.",1:"Session is oriented towards facilitation skills, practice or experience.",2:"Session clearly develops facilitation-specific skills and expertise, or develops personal facilitation practice or business."}},
  { key:"content", order:2, title:"Session Content", question:"Is the content of the session clearly explained, appropriate for the time available, and with clear benefits for participants?", isGate:false, anchors:{0:"It is unclear what the session would cover, how it might benefit participants, or the timing has not been fully considered.",1:"It is clear what the session would cover and what the benefits are, and there is recognition of the time limitation.",2:"The session content is well explained with clear benefits to participants. The content could easily be achieved within the allocated time."}},
  { key:"interactivity", order:3, title:"Interactivity", question:"Are appropriate methods planned to engage participants throughout, and has the session host considered how they would limit their own role?", isGate:false, anchors:{0:"Limited ideas for participation, with a focus on the session host presenting and sharing expertise.",1:"Plans have been made for participation throughout the session, and there is recognition of the host's role as a supporter of the learning experience.",2:"Varied methods for participation are proposed, with a clear statement of intent from the session host to support the learning experience rather than dominate it."}},
  { key:"credibility", order:4, title:"Credibility and Experience", question:"Does the session host have relevant facilitation experience of working with large groups, and with groups where English is not the primary language?", isGate:false, anchors:{0:"Limited experience of working with either large groups or groups where English is not the primary language.",1:"Has experience of working with large groups and with groups where English is not the primary language.",2:"Has many examples and experiences of working with large groups and with groups where English is not the primary language, across a range of settings."}},
] as const;
export const MAX_PRIMARY_SCORE = 8;
export function deriveIafStanding(q17:string,q18:string):0|1|2{ if(q17!=="yes") return 0; const acc=q18==="endorsed_facilitator"||q18==="certified_professional_facilitator"||q18==="certified_professional_facilitator_master"; return acc?2:1; }
export const QUALITY_DEFAULTS = { minMeanTotal:5.0, minMeanPerCriterion:1.0, gateCriterion:"focus" as CriterionKey, gateMinimum:1.0 };
